version: 2                                                                                                           

models:
  - name: stg__customers
    description: "Staging table for customer data ingested from the raw source. This model cleans and standardizes customer information for downstream use."
    columns:
      - name: customer_id
        data_type: int64
        description: "Unique ID for each customer"
        tests:
          - unique
          - not_null

      - name: customer_name
        data_type: string
        description: "Full name of the customer"
        tests:
          - not_null

      - name: email
        data_type: string
        description: "Unique email address for each customer"
        tests:
          - not_null
          - unique

      - name: address
        data_type: string
        description: "Mailing address"

      - name: payment_method
        data_type: string
        description: "Preferred payment method"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Credit', 'Debit', 'Paypal']

  - name: stg__subscriptions
    description: "Staging table for subscription data ingested from the raw source. This model cleans and standardizes subscription information for downstream use."
    columns:
      - name: subscription_id
        data_type: int64
        description: "Unique ID for each subscription record"
        tests:
          - unique
          - not_null

      - name: customer_id
        data_type: int64
        description: "The customer associated with this subscription"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg__customers')
                field: customer_id

      - name: plan_id
        data_type: int64
        description: "The plan this subscription belongs to"
        tests:
          - not_null

      - name: start_date
        data_type: date
        description: "Date when the subscription started"
        tests:
          - not_null

      - name: end_date
        data_type: date
        description: "Date when the subscription ended"

      - name: status
        data_type: string
        description: "Current status of the subscription"
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['active', 'cancelled', 'upgraded', 'downgraded']

      - name: cancel_date
        data_type: date
        description: "Date when the subscription was cancelled"

  - name: stg__invoices
    description: "Staging table for invoice data ingested from the raw source. This model cleans and standardizes invoice information for downstream use."
    columns:
      - name: invoice_id
        data_type: int64
        description: "Unique ID for each invoice"
        tests:
          - not_null

      - name: subscription_id
        data_type: int64
        description: "The subscription associated with this invoice"
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg__subscriptions')
                field: subscription_id


      - name: invoice_date
        data_type: date
        description: "Date when the invoice was generated"
        tests:
          - not_null

      - name: amount_due
        data_type: float64
        description: "The amount due on the invoice before any payments or discounts"
        tests:
          - not_null

      - name: invoice_status
        data_type: string
        description: "The current status of the invoice"
        tests:
          - not_null